In [1]:
%reload_ext sql
%config SqlMagic.displaycon = False
%config SqlMagic.autolimit = 100

In [2]:
%sql sqlite:///categories-socio-nord.db

Le but de ce TP est de découvrir le langage SQL sur des données réelles simples. 

Nous utiliserons des données issues de la base ouverte
[opendata.lillemetropole.fr/](https://opendata.lillemetropole.fr/),
plus précisément les données sur la population des communes du Nord en
2012 [téléchargeables ici](https://opendata.lillemetropole.fr/explore/dataset/evolution-et-structure-de-la-population-france-2012-categories-socio-professionn/information/).

Les données ont été récupérées et organisées en deux tables pour simplifier leur manipulation :

* la table *ville*
  - composée de cinq attributs de type TEXT appelés `code`, `region`,
  `departement`, `nom`, `coordonnees`. 
  - l'attribut `code` est la clé primaire. 
*  la table *evolution*
   - composée de quatre attributs appelés `code`, `categorie`,
	 `genre`, `effectif`.
   -  les attributs `code`, `categorie`, `sexe` sont de type TEXT et
	  `effectif` est de type INTEGER.
   - l'attribut `code` est une clé étrangère référençant l'attribut
    `code` de la table *ville*.

## Préparation 

Récupérez le fichier
[categories-socio-nord.db](./categories-socio-nord.db) et ouvrez-le
à l'aide de l'application
[DB Browser for SQLite - sqlitebrowser.org/](https://sqlitebrowser.org/). 

Cette application est un client du SGBD (Système de gestion de bases
de données) SQLite qui permet de manipuler les tables et leur contenu
de façon simplifiée et graphique.  
Vous devez le télécharger et l'installer sur votre poste.

## Consultation des données

Le DB Browser permet de consulter les données présentes dans chaque table,
à l'aide de l'onglet "Parcourir les données".

* Les attributs, aussi appelés champs, sont représentés en colonnes.
* Les enregistrements, aussi appelés entrées, sont représentés en lignes.

Vous pouvez noter le nombre d'enregistrements des deux tables, cela vous aidera à mieux comprendre ce qu'il se passe lors de l'exécution de certaines requêtes.

## Extraction de données

Le DB Browser permet d'exécuter des requêtes SQL, à l'aide de l'onglet
"Exécuter le SQL".

* `SELECT` : en SQL, permet de sélectionner tout ou partie des données d'une ou plusieurs tables de la base. 

Testez les requêtes suivantes, en essayant de deviner à l'avance ce que
la requête va afficher et le nombre de lignes qui seront affichées.

Certaines requêtes génèrent des erreurs, c'est voulu.

Si vous copiez-collez plusieurs requêtes à la suite,
seule l'exécution de la dernière sera visible. Vous pouvez exécuter les
requêtes une par une en mettant les autres en commentaire en ajoutant
`--` devant celles-ci. Vous pouvez aussi surligner la requête que vous
souhaitez exécuter et cliquer sur le bouton pour exécuter le code.
    
### Extraction de données d'une seule table

```sql    
SELECT * FROM ville;
SELECT nom, code FROM ville;
```

→ On peut renommer les colonnes pour un affichage plus explicite

```sql
SELECT nom AS LIBELLE, code FROM ville;
```

→ `DISTINCT` élimine les doublons

```sql
SELECT code FROM evolution;
SELECT DISTINCT code FROM evolution;
```

→ `ORDER BY` ordonne les résultats

```sql    
SELECT DISTINCT code FROM evolution ORDER BY code DESC;
```

→ La clause `WHERE` permet de préciser un critère pour filtrer les données

```sql
SELECT * FROM ville WHERE code='59140';
SELECT nom, code FROM ville WHERE code='67340';
SELECT nom, code FROM ville WHERE code='59140' OR code='59260';
SELECT * FROM evolution WHERE code='59140';
```

→ On peut récupérer le `MIN`, le `MAX`, le nombre de lignes avec
`COUNT` ou la moyenne d'un attribut numérique avec `AVG` (_average_,
moyenne en anglais)

```sql
SELECT MIN(nom) AS MIN FROM ville;
SELECT COUNT(*) AS NbLignes FROM ville;
SELECT MAX(effectif) AS MAX, MIN(effectif) AS MIN, SUM(effectif) AS TOTAL, AVG(effectif) AS MOYENNE FROM evolution;
```

#### C'est à vous !

Construisez les requêtes permettant d'afficher les données qui répondent
aux questions suivantes.

1. Quels sont les différents libellés des catégories socioprofessionnelles par ordre alphabétique croissant ?

2. Combien de catégories différentes sont utilisées dans ce jeu de données ?

3. Quel est le code INSEE de Caullery ?

4. Affichez toutes les informations de la table évolution pour la ville de Caullery (en utilisant le code INSEE), triées par effectifs croissants.

5. Quels sont les codes postaux des villes ayant des catégories socioprofessionnelles dont les effectifs dépassent 2000 individus ?

6. Combien y a-t-il de femmes agricultrices dans le Nord ?

7. Quel est le nombre moyen d'employés par commune dans le Nord ?

In [3]:
%%sql

SELECT DISTINCT categorie
FROM evolution
ORDER BY categorie ASC;

Done.

[('Agriculteurs Exploitants',),
 ("Artisans, Commerçants ,Chefs d'entreprises",),
 ('Autres',),
 ('Cadres, Professions Intellectuelles Supérieures',),
 ('Employés',),
 ('Ouvriers',),
 ('Professions Intermédiaires',),
 ('Retraités',)]

In [6]:
%%sql

SELECT COUNT(DISTINCT categorie)
FROM evolution

Done.

[(8,)]

In [7]:
%%sql

SELECT code
FROM ville
WHERE nom='Caullery';

Done.

[('59140',)]

In [9]:
%%sql

SELECT * 
FROM
evolution
WHERE code = (SELECT code
FROM ville
WHERE nom='Caullery')
ORDER BY  effectif ASC;

Done.

[('59317', 'Agriculteurs Exploitants', 'Femmes', 4),
 ('59317', 'Agriculteurs Exploitants', 'Hommes', 4),
 ('59317', "Artisans, Commerçants ,Chefs d'entreprises", 'Femmes', 28),
 ('59317', "Artisans, Commerçants ,Chefs d'entreprises", 'Hommes', 111),
 ('59317', 'Cadres, Professions Intellectuelles Supérieures', 'Femmes', 154),
 ('59317', 'Ouvriers', 'Femmes', 194),
 ('59317', 'Cadres, Professions Intellectuelles Supérieures', 'Hommes', 226),
 ('59317', 'Employés', 'Hommes', 261),
 ('59317', 'Autres', 'Hommes', 416),
 ('59317', 'Professions Intermédiaires', 'Hommes', 432),
 ('59317', 'Professions Intermédiaires', 'Femmes', 463),
 ('59317', 'Autres', 'Femmes', 563),
 ('59317', 'Retraités', 'Hommes', 598),
 ('59317', 'Retraités', 'Femmes', 824),
 ('59317', 'Ouvriers', 'Hommes', 831),
 ('59317', 'Employés', 'Femmes', 966)]

In [10]:
%%sql

SELECT DISTINCT code 
FROM
evolution
WHERE
effectif > 2000;

Done.

[('59392',),
 ('59599',),
 ('59183',),
 ('59378',),
 ('59279',),
 ('59512',),
 ('59650',),
 ('59155',),
 ('59178',),
 ('59328',),
 ('59606',),
 ('59350',),
 ('59271',),
 ('59043',),
 ('59569',),
 ('59122',),
 ('59507',),
 ('59220',),
 ('59360',),
 ('59410',),
 ('59163',),
 ('59009',),
 ('59368',),
 ('59172',),
 ('59295',),
 ('59017',),
 ('59646',),
 ('59299',),
 ('59526',)]

In [13]:
%%sql

SELECT
SUM(effectif)
FROM
evolution
WHERE genre = 'Femmes' AND categorie LIKE '%Agriculteurs%';

Done.

[(1911,)]

In [15]:
%%sql

SELECT ROUND(AVG(effectif),1)
FROM evolution
WHERE categorie LIKE '%Employés%'

Done.

[(260.2,)]

### Extraction croisée de données de plusieurs tables

Observez les lignes, le nombre de lignes et le nombre de colonnes
des résultats des requêtes montrées en exemple.
Essayez d'en déduire le croisement qui a été fait.

→ Produit cartésien

```sql
SELECT * FROM ville, evolution;
SELECT * FROM ville, evolution WHERE nom='Caullery';
SELECT code, nom
    FROM ville, evolution
    WHERE nom='Caullery';
```

→ Attributs qui ont le même nom dans des tables différentes

Lorsque des attributs ont le même nom dans des tables différentes,
il est nécessaire de préciser le nom de la table dont viennent les
données que l'on veut afficher.

```sql
SELECT ville.code AS code1, evolution.code AS code2, nom
    FROM ville, evolution
    WHERE nom='Caullery';
```

→ On peut renommer les tables

```sql
SELECT nom, v.code AS code1, effectif
    FROM ville AS v, evolution AS e
    WHERE nom='Caullery';
```

→ Si on renomme une table, seul le nouveau nom existe dans la requête

```sql
SELECT nom, ville.code AS code1, e.code AS code2, effectif
    FROM ville AS v, evolution AS e
    WHERE nom='Caullery';
```

→ Utilisation de la jointure entre tables : `JOIN`

```sql
SELECT v.code, nom AS ville, categorie, genre, effectif
    FROM ville AS v JOIN evolution AS e ON v.code=e.code
    WHERE nom='Caullery';
```

Attention ! Il faut préciser sur quelles clés la jointure doit être
faite.

→ Un exemple de sous-requête, pas explicitement au programme

```sql
SELECT v.code AS code, nom, categorie, genre, effectif
    FROM ville AS v JOIN evolution AS e ON v.code=e.code
    WHERE  effectif=(SELECT max(effectif) FROM evolution);
```

In [18]:
%%sql

--requête qui n'a aucun sens, on associe toutes les lignes de ville à toutes les lignes d'evolution

SELECT * FROM ville, evolution WHERE nom='Caullery';

Done.

[('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59120', 'Professions Intermédiaires', 'Femmes', 128),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59137', 'Professions Intermédiaires', 'Hommes', 8),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59648', "Artisans, Commerçants ,Chefs d'entreprises", 'Hommes', 173),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59288', 'Retraités', 'Hommes', 230),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59033', 'Employés', 'Femmes', 878),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59596', 'Cadres, Professions Intellectuelles Supérieures', 'Hommes', 28),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59228', 'Cadres, Professions Intellectuelles Supérieures', 'Femmes', 44),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59515', 'Employés', 'Femmes', 70),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59353', 'Autres', 'Hommes', 8),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59002', 'Agriculteurs Exploitants', 'Hommes', 8),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59111', 'Agriculteurs Exploitants', 'Femmes', 4),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59192', 'Autres', 'Femmes', 97),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59383', 'Employés', 'Hommes', 330),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59343', 'Autres', 'Hommes', 302),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59343', 'Ouvriers', 'Femmes', 113),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59370', 'Cadres, Professions Intellectuelles Supérieures', 'Hommes', 49),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59564', 'Professions Intermédiaires', 'Femmes', 155),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59053', 'Employés', 'Femmes', 390),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59226', 'Employés', 'Femmes', 157),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59535', 'Ouvriers', 'Hommes', 144),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59498', "Artisans, Commerçants ,Chefs d'entreprises", 'Hommes', 21),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59105', 'Employés', 'Femmes', 164),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59251', 'Employés', 'Femmes', 20),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59579', 'Professions Intermédiaires', 'Femmes', 118),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59392', 'Cadres, Professions Intellectuelles Supérieures', 'Hommes', 594),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59471', 'Agriculteurs Exploitants', 'Hommes', 4),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59189', 'Retraités', 'Femmes', 73),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59358', 'Retraités', 'Femmes', 96),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59443', 'Agriculteurs Exploitants', 'Hommes', 12),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59497', 'Cadres, Professions Intellectuelles Supérieures', 'Hommes', 44),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59455', 'Employés', 'Hommes', 28),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59055', 'Professions Intermédiaires', 'Femmes', 20),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59264', 'Agriculteurs Exploitants', 'Femmes', 0),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59259', 'Agriculteurs Exploitants', 'Hommes', 0),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59427', 'Employés', 'Hommes', 12),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59280', "Artisans, Commerçants ,Chefs d'entreprises", 'Hommes', 4),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59185', 'Cadres, Professions Intellectuelles Supérieures', 'Femmes', 12),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59022', 'Cadres, Professions Intellectuelles Supérieures', 'Hommes', 192),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59409', 'Agriculteurs Exploitants', 'Femmes', 0),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59457', 'Professions Intermédiaires', 'Hommes', 452),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59006', "Artisans, Commerçants ,Chefs d'entreprises", 'Femmes', 0),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59419', 'Autres', 'Femmes', 84),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59297', 'Agriculteurs Exploitants', 'Hommes', 0),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59329', 'Cadres, Professions Intellectuelles Supérieures', 'Hommes', 219),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59113', 'Retraités', 'Hommes', 76),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59157', "Artisans, Commerçants ,Chefs d'entreprises", 'Femmes', 23),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59412', 'Professions Intermédiaires', 'Hommes', 4),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59223', 'Retraités', 'Femmes', 44),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59616', 'Agriculteurs Exploitants', 'Hommes', 6),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59136', 'Autres', 'Femmes', 908),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59452', 'Autres', 'Hommes', 250),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59476', 'Autres', 'Hommes', 168),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59148', 'Professions Intermédiaires', 'Femmes', 25),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59511', 'Cadres, Professions Intellectuelles Supérieures', 'Hommes', 92),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59494', 'Employés', 'Femmes', 17),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59399', 'Cadres, Professions Intellectuelles Supérieures', 'Hommes', 32),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59335', 'Employés', 'Hommes', 38),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59383', 'Retraités', 'Femmes', 1414),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59043', 'Agriculteurs Exploitants', 'Femmes', 19),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59538', 'Employés', 'Femmes', 14),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59559', 'Employés', 'Femmes', 132),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59523', 'Agriculteurs Exploitants', 'Femmes', 0),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59198', 'Ouvriers', 'Hommes', 15),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59069', 'Retraités', 'Femmes', 75),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59031', 'Employés', 'Femmes', 44),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59014', 'Retraités', 'Hommes', 1037),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59076', 'Autres', 'Femmes', 39),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59191', 'Agriculteurs Exploitants', 'Hommes', 8),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59488', 'Employés', 'Hommes', 86),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59438', 'Employés', 'Hommes', 8),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59446', 'Autres', 'Hommes', 25),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59444', 'Employés', 'Femmes', 86),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59251', "Artisans, Commerçants ,Chefs d'entreprises", 'Hommes', 4),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59375', 'Professions Intermédiaires', 'Hommes', 308),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59013', 'Retraités', 'Femmes', 147),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59472', 'Professions Intermédiaires', 'Femmes', 52),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59009', 'Agriculteurs Exploitants', 'Hommes', 9),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59130', 'Ouvriers', 'Hommes', 100),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59137', "Artisans, Commerçants ,Chefs d'entreprises", 'Femmes', 4),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59646', "Artisans, Commerçants ,Chefs d'entreprises", 'Hommes', 412),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59661', 'Autres', 'Femmes', 10),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59517', 'Autres', 'Femmes', 72),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59471', 'Autres', 'Hommes', 72),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59039', 'Professions Intermédiaires', 'Femmes', 84),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59363', 'Cadres, Professions Intellectuelles Supérieures', 'Hommes', 36),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59403', 'Professions Intermédiaires', 'Femmes', 28),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59346', 'Cadres, Professions Intellectuelles Supérieures', 'Hommes', 285),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59583', 'Agriculteurs Exploitants', 'Hommes', 4),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59229', 'Cadres, Professions Intellectuelles Supérieures', 'Hommes', 20),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59113', 'Employés', 'Femmes', 157),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59169', 'Employés', 'Hommes', 13),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59659', 'Professions Intermédiaires', 'Hommes', 40),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59038', 'Employés', 'Hommes', 35),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59359', 'Ouvriers', 'Femmes', 112),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59173', 'Cadres, Professions Intellectuelles Supérieures', 'Hommes', 72),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59023', 'Retraités', 'Femmes', 42),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59073', 'Retraités', 'Hommes', 52),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59357', 'Agriculteurs Exploitants', 'Hommes', 8),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59382', 'Retraités', 'Hommes', 156),
 ('59140', '31', '59', 'Caullery', '50.0824546804,3.37276572782', '59341', 'Professions Intermédiaires', 'Femmes', 36)]

### C'est à vous!

Construisez les requêtes permettant d'afficher les données qui répondent
aux questions suivantes.

1. Affichez les catégories socioprofessionnelles, genres et effectifs
pour la ville de Caullery, sans utiliser le code INSEE, triées par effectifs croissants.

2. Affichez les noms des villes, ainsi que les catégories et genres
des données ayant des effectifs à 0, triés par catégories.

3. Quelles sont les noms des villes ayant des catégories socioprofessionnelles dont les effectifs dépassent 2000 individus ?

4. Ordonnez le résultat par effectifs décroissants. 

5. Même question en supprimant la ville de Lille des résultats
   possibles.

In [20]:
%%sql

SELECT categorie, genre, effectif
FROM ville JOIN evolution
ON ville.code=evolution.code
WHERE nom='Caullery'
ORDER BY effectif ASC;

Done.

[('Cadres, Professions Intellectuelles Supérieures', 'Femmes', 0),
 ('Professions Intermédiaires', 'Hommes', 0),
 ('Agriculteurs Exploitants', 'Femmes', 0),
 ('Autres', 'Hommes', 4),
 ('Agriculteurs Exploitants', 'Hommes', 8),
 ("Artisans, Commerçants ,Chefs d'entreprises", 'Femmes', 8),
 ('Cadres, Professions Intellectuelles Supérieures', 'Hommes', 12),
 ('Employés', 'Hommes', 12),
 ("Artisans, Commerçants ,Chefs d'entreprises", 'Hommes', 12),
 ('Ouvriers', 'Femmes', 24),
 ('Professions Intermédiaires', 'Femmes', 28),
 ('Employés', 'Femmes', 32),
 ('Retraités', 'Hommes', 44),
 ('Autres', 'Femmes', 44),
 ('Ouvriers', 'Hommes', 60),
 ('Retraités', 'Femmes', 64)]

In [23]:
%%sql

SELECT categorie, genre, nom, effectif
FROM ville JOIN evolution
ON ville.code=evolution.code
WHERE effectif=0
ORDER BY categorie ASC;

Done.

[('Agriculteurs Exploitants', 'Femmes', 'Gognies-Chaussée', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Ghissignies', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Monchecourt', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Hélesmes', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Sainghin-en-Mélantois', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Zuydcoote', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Bachy', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Roeulx', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Féron', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Camphin-en-Carembault', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Anhiers', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Moustier-en-Fagne', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Gruson', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Flers-en-Escrebieux', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Busigny', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Crochte', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Neuf-Berquin', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Saméon', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Marpent', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Ghissignies', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Chemy', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Englos', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Les Rues-des-Vignes', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Roncq', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Solre-le-Château', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Nivelle', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Loffre', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Raimbeaucourt', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Vendeville', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Wavrechain-sous-Faulx', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Hallennes-lez-Haubourdin', 0),
 ('Agriculteurs Exploitants', 'Femmes', "Bruay-sur-l'Escaut", 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Capelle', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Maretz', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Gonnelieu', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Roucourt', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Clairfayts', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Orchies', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Bersillies', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Banteux', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Don', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Maulde', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Mouchin', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Sars-et-Rosières', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Phalempin', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Trith-Saint-Léger', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Cuincy', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Provin', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Le Maisnil', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Lauwin-Planque', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Haynecourt', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Croix-Caluyau', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'La Flamengrie', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Potelle', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Hem', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Lieu-Saint-Amand', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Armentières', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Oisy', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Troisvilles', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Bettrechies', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Cerfontaine', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Écaillon', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Vieux-Mesnil', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Cantaing-sur-Escaut', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Dechy', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Brunémont', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Mortagne-du-Nord', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Sains-du-Nord', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Haulchin', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Trith-Saint-Léger', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Wavrechain-sous-Faulx', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Monchaux-sur-Écaillon', 0),
 ('Agriculteurs Exploitants', 'Femmes', "Crèvecoeur-sur-l'Escaut", 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Bugnicourt', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Iwuy', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Aubencheul-au-Bac', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Neuville-Saint-Rémy', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Beaurain', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Sebourg', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Montay', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Bourghelles', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Louvroil', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Sommaing', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Férin', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Villereau', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Lieu-Saint-Amand', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Colleret', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Lécluse', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Bousies', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Raucourt-au-Bois', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Vertain', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Loos', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Ronchin', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Aniche', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Marly', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Hestrud', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Avesnes-sur-Helpe', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Bas-Lieu', 0),
 ('Agriculteurs Exploitants', 'Femmes', 'Hérin', 0),
 ('Agriculteurs Exploitants', 'Hommes', 'Émerchicourt', 0)]

In [34]:
%%sql
SELECT DISTINCT nom 
FROM
(
SELECT nom, categorie, SUM(effectif)
FROM ville JOIN evolution
ON ville.code=evolution.code
GROUP BY nom, categorie
HAVING SUM(effectif) > 2000
)
;

Done.

[('Aniche',),
 ('Anzin',),
 ('Armentières',),
 ('Bailleul',),
 ('Bondues',),
 ("Bruay-sur-l'Escaut",),
 ('Cambrai',),
 ('Caudry',),
 ('Comines',),
 ("Condé-sur-l'Escaut",),
 ('Coudekerque-Branche',),
 ('Croix',),
 ('Denain',),
 ('Douai',),
 ('Douchy-les-Mines',),
 ('Dunkerque',),
 ('Faches-Thumesnil',),
 ('Fourmies',),
 ('Grande-Synthe',),
 ('Gravelines',),
 ('Halluin',),
 ('Haubourdin',),
 ('Hautmont',),
 ('Hazebrouck',),
 ('Hem',),
 ('Jeumont',),
 ('La Madeleine',),
 ('Lambersart',),
 ('Leers',),
 ('Lille',),
 ('Loos',),
 ('Lys-lez-Lannoy',),
 ('Marcq-en-Baroeul',),
 ('Marly',),
 ('Maubeuge',),
 ('Mons-en-Baroeul',),
 ('Mouvaux',),
 ('Neuville-en-Ferrain',),
 ('Raismes',),
 ('Ronchin',),
 ('Roncq',),
 ('Roubaix',),
 ('Saint-Amand-les-Eaux',),
 ('Saint-André-lez-Lille',),
 ('Saint-Saulve',),
 ('Seclin',),
 ('Sin-le-Noble',),
 ('Somain',),
 ('Tourcoing',),
 ('Valenciennes',),
 ('Vieux-Condé',),
 ("Villeneuve-d'Ascq",),
 ('Wambrechies',),
 ('Wasquehal',),
 ('Wattignies',),
 ('Wattrelos',)]

In [35]:
%%sql
SELECT nom, categorie, SUM(effectif)
FROM ville JOIN evolution
ON ville.code=evolution.code
GROUP BY nom, categorie
HAVING SUM(effectif) > 2000
ORDER BY effectif DESC
;

Done.

[('Lille', 'Autres', 56001),
 ('Lille', 'Cadres, Professions Intellectuelles Supérieures', 28963),
 ('Lille', 'Professions Intermédiaires', 29446),
 ('Lille', 'Ouvriers', 16678),
 ('Dunkerque', 'Retraités', 20723),
 ('Lille', 'Retraités', 28549),
 ('Tourcoing', 'Ouvriers', 14226),
 ('Lille', 'Employés', 29818),
 ('Dunkerque', 'Autres', 15116),
 ('Tourcoing', 'Autres', 14713),
 ('Tourcoing', 'Retraités', 14259),
 ('Roubaix', 'Employés', 11526),
 ('Roubaix', 'Autres', 21386),
 ("Villeneuve-d'Ascq", 'Autres', 12962),
 ('Roubaix', 'Retraités', 12440),
 ('Wattrelos', 'Ouvriers', 7228),
 ('Douai', 'Autres', 8880),
 ('Dunkerque', 'Professions Intermédiaires', 9387),
 ('Maubeuge', 'Autres', 7300),
 ("Villeneuve-d'Ascq", 'Retraités', 8030),
 ('Wattrelos', 'Retraités', 7879),
 ('Tourcoing', 'Professions Intermédiaires', 8701),
 ("Villeneuve-d'Ascq", 'Professions Intermédiaires', 8131),
 ('Douai', 'Ouvriers', 5146),
 ('Valenciennes', 'Autres', 9157),
 ('Douai', 'Employés', 5496),
 ('Wattrelos', 'Autres', 5836),
 ('Valenciennes', 'Ouvriers', 4145),
 ('Maubeuge', 'Ouvriers', 4101),
 ('Marcq-en-Baroeul', 'Autres', 5410),
 ('Denain', 'Autres', 4976),
 ('Lambersart', 'Retraités', 5770),
 ('Tourcoing', 'Employés', 13230),
 ('Marcq-en-Baroeul', 'Retraités', 8024),
 ('Douai', 'Retraités', 7443),
 ('Roubaix', 'Professions Intermédiaires', 6727),
 ('Roubaix', 'Ouvriers', 12849),
 ('Valenciennes', 'Retraités', 7895),
 ('Marcq-en-Baroeul', 'Professions Intermédiaires', 5077),
 ('Armentières', 'Employés', 3729),
 ('Cambrai', 'Retraités', 7394),
 ('Maubeuge', 'Employés', 3636),
 ('Grande-Synthe', 'Ouvriers', 3258),
 ('Dunkerque', 'Employés', 12428),
 ('Maubeuge', 'Retraités', 6059),
 ('Coudekerque-Branche', 'Retraités', 4701),
 ('Dunkerque', 'Cadres, Professions Intellectuelles Supérieures', 4183),
 ('Denain', 'Ouvriers', 2999),
 ('Marcq-en-Baroeul', 'Cadres, Professions Intellectuelles Supérieures', 6461),
 ('Lambersart', 'Cadres, Professions Intellectuelles Supérieures', 4253),
 ("Villeneuve-d'Ascq", 'Cadres, Professions Intellectuelles Supérieures', 6224),
 ('Mons-en-Baroeul', 'Autres', 3840),
 ('Valenciennes', 'Professions Intermédiaires', 5182),
 ("Villeneuve-d'Ascq", 'Employés', 8546),
 ('La Madeleine', 'Retraités', 3819),
 ('Lambersart', 'Autres', 3862),
 ('Halluin', 'Ouvriers', 3010),
 ('Croix', 'Retraités', 3736),
 ('Faches-Thumesnil', 'Retraités', 3940),
 ('Grande-Synthe', 'Employés', 2748),
 ('Lambersart', 'Employés', 2947),
 ('Hazebrouck', 'Retraités', 4936),
 ('Sin-le-Noble', 'Autres', 3169),
 ('La Madeleine', 'Employés', 2907),
 ('Ronchin', 'Retraités', 3472),
 ('Croix', 'Employés', 2665),
 ('Hautmont', 'Autres', 2971),
 ('Anzin', 'Autres', 2826),
 ('La Madeleine', 'Professions Intermédiaires', 3440),
 ('Cambrai', 'Autres', 5213),
 ('Ronchin', 'Employés', 2665),
 ('Douai', 'Professions Intermédiaires', 4046),
 ('Roubaix', 'Cadres, Professions Intellectuelles Supérieures', 3070),
 ('Caudry', 'Retraités', 3236),
 ('Hazebrouck', 'Autres', 3093),
 ('Croix', 'Autres', 3081),
 ('Wattrelos', 'Professions Intermédiaires', 3822),
 ('Dunkerque', 'Ouvriers', 11449),
 ('Armentières', 'Retraités', 4714),
 ('Caudry', 'Ouvriers', 2368),
 ('Saint-Amand-les-Eaux', 'Employés', 2266),
 ('Hautmont', 'Ouvriers', 2173),
 ('Haubourdin', 'Retraités', 2835),
 ('Saint-Amand-les-Eaux', 'Autres', 2697),
 ('Mons-en-Baroeul', 'Ouvriers', 2205),
 ('Halluin', 'Autres', 2769),
 ('Fourmies', 'Retraités', 2956),
 ('Armentières', 'Autres', 4216),
 ('Sin-le-Noble', 'Retraités', 3076),
 ('Fourmies', 'Autres', 2625),
 ('Cambrai', 'Professions Intermédiaires', 3253),
 ('Anzin', 'Ouvriers', 2030),
 ('Bailleul', 'Employés', 2210),
 ('Denain', 'Employés', 2093),
 ('Valenciennes', 'Employés', 5477),
 ('Halluin', 'Retraités', 3564),
 ('Lambersart', 'Professions Intermédiaires', 4040),
 ('Wasquehal', 'Retraités', 4001),
 ('Croix', 'Ouvriers', 2039),
 ('Jeumont', 'Autres', 2291)]

In [36]:
%%sql
SELECT nom, categorie, SUM(effectif)
FROM ville JOIN evolution
ON ville.code=evolution.code
WHERE nom != 'Lille'
GROUP BY nom, categorie
HAVING SUM(effectif) > 2000
ORDER BY effectif DESC
;

Done.

[('Dunkerque', 'Retraités', 20723),
 ('Tourcoing', 'Ouvriers', 14226),
 ('Dunkerque', 'Autres', 15116),
 ('Tourcoing', 'Autres', 14713),
 ('Tourcoing', 'Retraités', 14259),
 ('Roubaix', 'Employés', 11526),
 ('Roubaix', 'Autres', 21386),
 ("Villeneuve-d'Ascq", 'Autres', 12962),
 ('Roubaix', 'Retraités', 12440),
 ('Wattrelos', 'Ouvriers', 7228),
 ('Douai', 'Autres', 8880),
 ('Dunkerque', 'Professions Intermédiaires', 9387),
 ('Maubeuge', 'Autres', 7300),
 ("Villeneuve-d'Ascq", 'Retraités', 8030),
 ('Wattrelos', 'Retraités', 7879),
 ('Tourcoing', 'Professions Intermédiaires', 8701),
 ("Villeneuve-d'Ascq", 'Professions Intermédiaires', 8131),
 ('Douai', 'Ouvriers', 5146),
 ('Valenciennes', 'Autres', 9157),
 ('Douai', 'Employés', 5496),
 ('Wattrelos', 'Autres', 5836),
 ('Valenciennes', 'Ouvriers', 4145),
 ('Maubeuge', 'Ouvriers', 4101),
 ('Marcq-en-Baroeul', 'Autres', 5410),
 ('Denain', 'Autres', 4976),
 ('Lambersart', 'Retraités', 5770),
 ('Tourcoing', 'Employés', 13230),
 ('Marcq-en-Baroeul', 'Retraités', 8024),
 ('Douai', 'Retraités', 7443),
 ('Roubaix', 'Professions Intermédiaires', 6727),
 ('Roubaix', 'Ouvriers', 12849),
 ('Valenciennes', 'Retraités', 7895),
 ('Marcq-en-Baroeul', 'Professions Intermédiaires', 5077),
 ('Armentières', 'Employés', 3729),
 ('Cambrai', 'Retraités', 7394),
 ('Maubeuge', 'Employés', 3636),
 ('Grande-Synthe', 'Ouvriers', 3258),
 ('Dunkerque', 'Employés', 12428),
 ('Maubeuge', 'Retraités', 6059),
 ('Coudekerque-Branche', 'Retraités', 4701),
 ('Dunkerque', 'Cadres, Professions Intellectuelles Supérieures', 4183),
 ('Denain', 'Ouvriers', 2999),
 ('Marcq-en-Baroeul', 'Cadres, Professions Intellectuelles Supérieures', 6461),
 ('Lambersart', 'Cadres, Professions Intellectuelles Supérieures', 4253),
 ("Villeneuve-d'Ascq", 'Cadres, Professions Intellectuelles Supérieures', 6224),
 ('Mons-en-Baroeul', 'Autres', 3840),
 ('Valenciennes', 'Professions Intermédiaires', 5182),
 ("Villeneuve-d'Ascq", 'Employés', 8546),
 ('La Madeleine', 'Retraités', 3819),
 ('Lambersart', 'Autres', 3862),
 ('Halluin', 'Ouvriers', 3010),
 ('Croix', 'Retraités', 3736),
 ('Faches-Thumesnil', 'Retraités', 3940),
 ('Grande-Synthe', 'Employés', 2748),
 ('Lambersart', 'Employés', 2947),
 ('Hazebrouck', 'Retraités', 4936),
 ('Sin-le-Noble', 'Autres', 3169),
 ('La Madeleine', 'Employés', 2907),
 ('Ronchin', 'Retraités', 3472),
 ('Croix', 'Employés', 2665),
 ('Hautmont', 'Autres', 2971),
 ('Anzin', 'Autres', 2826),
 ('La Madeleine', 'Professions Intermédiaires', 3440),
 ('Cambrai', 'Autres', 5213),
 ('Ronchin', 'Employés', 2665),
 ('Douai', 'Professions Intermédiaires', 4046),
 ('Roubaix', 'Cadres, Professions Intellectuelles Supérieures', 3070),
 ('Caudry', 'Retraités', 3236),
 ('Hazebrouck', 'Autres', 3093),
 ('Croix', 'Autres', 3081),
 ('Wattrelos', 'Professions Intermédiaires', 3822),
 ('Dunkerque', 'Ouvriers', 11449),
 ('Armentières', 'Retraités', 4714),
 ('Caudry', 'Ouvriers', 2368),
 ('Saint-Amand-les-Eaux', 'Employés', 2266),
 ('Hautmont', 'Ouvriers', 2173),
 ('Haubourdin', 'Retraités', 2835),
 ('Saint-Amand-les-Eaux', 'Autres', 2697),
 ('Mons-en-Baroeul', 'Ouvriers', 2205),
 ('Halluin', 'Autres', 2769),
 ('Fourmies', 'Retraités', 2956),
 ('Armentières', 'Autres', 4216),
 ('Sin-le-Noble', 'Retraités', 3076),
 ('Fourmies', 'Autres', 2625),
 ('Cambrai', 'Professions Intermédiaires', 3253),
 ('Anzin', 'Ouvriers', 2030),
 ('Bailleul', 'Employés', 2210),
 ('Denain', 'Employés', 2093),
 ('Valenciennes', 'Employés', 5477),
 ('Halluin', 'Retraités', 3564),
 ('Lambersart', 'Professions Intermédiaires', 4040),
 ('Wasquehal', 'Retraités', 4001),
 ('Croix', 'Ouvriers', 2039),
 ('Jeumont', 'Autres', 2291),
 ('Comines', 'Ouvriers', 2096),
 ('Grande-Synthe', 'Retraités', 3293),
 ('Loos', 'Autres', 3459),
 ('Mons-en-Baroeul', 'Retraités', 3545),
 ('Vieux-Condé', 'Autres', 2120),
 ('La Madeleine', 'Cadres, Professions Intellectuelles Supérieures', 3552)]

In [37]:
%%sql

SELECT nom
	FROM ville AS v JOIN evolution AS e ON v.code=e.code
	WHERE effectif > 2000 AND nom != "Lille"
	ORDER BY effectif DESC;

Done.

[('Roubaix',),
 ('Dunkerque',),
 ('Tourcoing',),
 ('Tourcoing',),
 ('Roubaix',),
 ('Dunkerque',),
 ('Dunkerque',),
 ('Dunkerque',),
 ('Tourcoing',),
 ('Dunkerque',),
 ('Tourcoing',),
 ('Roubaix',),
 ('Roubaix',),
 ("Villeneuve-d'Ascq",),
 ('Roubaix',),
 ("Villeneuve-d'Ascq",),
 ('Tourcoing',),
 ("Villeneuve-d'Ascq",),
 ('Tourcoing',),
 ('Roubaix',),
 ('Dunkerque',),
 ('Wattrelos',),
 ('Douai',),
 ('Valenciennes',),
 ('Valenciennes',),
 ('Marcq-en-Baroeul',),
 ('Dunkerque',),
 ('Maubeuge',),
 ("Villeneuve-d'Ascq",),
 ('Dunkerque',),
 ('Wattrelos',),
 ('Cambrai',),
 ('Wattrelos',),
 ('Tourcoing',),
 ("Villeneuve-d'Ascq",),
 ('Tourcoing',),
 ('Douai',),
 ('Douai',),
 ('Valenciennes',),
 ("Villeneuve-d'Ascq",),
 ('Marcq-en-Baroeul',),
 ('Douai',),
 ('Valenciennes',),
 ("Villeneuve-d'Ascq",),
 ("Villeneuve-d'Ascq",),
 ('Roubaix',),
 ('Wattrelos',),
 ('Tourcoing',),
 ('Douai',),
 ('Valenciennes',),
 ('Roubaix',),
 ('Maubeuge',),
 ('Marcq-en-Baroeul',),
 ('Denain',),
 ('Lambersart',),
 ("Villeneuve-d'Ascq",),
 ('Cambrai',),
 ('Maubeuge',),
 ('Tourcoing',),
 ('Wattrelos',),
 ('Cambrai',),
 ('Cambrai',),
 ('Grande-Synthe',),
 ('Marcq-en-Baroeul',),
 ('Douai',),
 ('Roubaix',),
 ('Roubaix',),
 ('Valenciennes',),
 ('Marcq-en-Baroeul',),
 ('Marcq-en-Baroeul',),
 ('Armentières',),
 ('Armentières',),
 ('Cambrai',),
 ('Armentières',),
 ('Hazebrouck',),
 ('Maubeuge',),
 ('Grande-Synthe',),
 ('Valenciennes',),
 ('Dunkerque',),
 ('Maubeuge',),
 ('Maubeuge',),
 ('Coudekerque-Branche',),
 ('Dunkerque',),
 ('Hazebrouck',),
 ('Denain',),
 ('Loos',),
 ('Marcq-en-Baroeul',),
 ('Coudekerque-Branche',),
 ('Lambersart',),
 ('Armentières',),
 ("Villeneuve-d'Ascq",),
 ('Mons-en-Baroeul',),
 ('Valenciennes',),
 ('Coudekerque-Branche',),
 ("Villeneuve-d'Ascq",),
 ('Hazebrouck',),
 ('Wasquehal',),
 ('Lambersart',),
 ('La Madeleine',),
 ('Lambersart',)]